import { Play as  Play} from 'lucide-react';
import Image from 'next/image';
export function PlayLists(){
    return (
        <div className="grid grid-cols-3 gap-4 mt-4">
            <a href="#" className="bg-white/5 rounded group flex items-center gap-4 overflow-hidden hover:bg-white/10 transition-colors"><Image src="/album1.jpg" width={104} height={104} alt="capado album"/><strong>PlayList Dioendtsx</strong><button className="w-12 h-12 flex items-center justify-center pl-1 rounded-full bg-green-400 text-black ml-auto mr-8 invisible group-hover:visible"><Play /></button></a>
            <a href="#" className="bg-white/5 rounded group flex items-center gap-4 overflow-hidden hover:bg-white/10 transition-colors"><Image src="/album02.jpg" width={104} height={104} alt="capado album"/><strong>Best Songs of 2023</strong><button className="w-12 h-12 flex items-center justify-center pl-1 rounded-full bg-green-400 text-black ml-auto mr-8 invisible group-hover:visible"><Play /></button></a>
            <a href="#" className="bg-white/5 rounded group flex items-center gap-4 overflow-hidden hover:bg-white/10 transition-colors"><Image src="/album03.jpg" width={104} height={104} alt="capado album"/><strong>90s Acoustic</strong><button className="w-12 h-12 flex items-center justify-center pl-1 rounded-full bg-green-400 text-black ml-auto mr-8 invisible group-hover:visible"><Play /></button></a>
            <a href="#" className="bg-white/5 rounded group flex items-center gap-4 overflow-hidden hover:bg-white/10 transition-colors"><Image src="/album04.jpg" width={104} height={104} alt="capado album"/><strong>O Melhor do Acústico MTV</strong><button className="w-12 h-12 flex items-center justify-center pl-1 rounded-full bg-green-400 text-black ml-auto mr-8 invisible group-hover:visible"><Play /></button></a>
            <a href="#" className="bg-white/5 rounded group flex items-center gap-4 overflow-hidden hover:bg-white/10 transition-colors"><Image src="/album05.jpg" width={104} height={104} alt="capado album"/><strong>CPM 22 - Acústico</strong><button className="w-12 h-12 flex items-center justify-center pl-1 rounded-full bg-green-400 text-black ml-auto mr-8 invisible group-hover:visible"><Play /></button></a>
            <a href="#" className="bg-white/5 rounded group flex items-center gap-4 overflow-hidden hover:bg-white/10 transition-colors"><Image src="/album06.jpg" width={104} height={104} alt="capado album"/><strong>Rock Forever</strong><button className="w-12 h-12 flex items-center justify-center pl-1 rounded-full bg-green-400 text-black ml-auto mr-8 invisible group-hover:visible"><Play /></button></a>
          </div>
    )
}